/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Nl0TfNbab27
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Gabarito } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"

export function product-detail-page() {
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="grid gap-4 md:gap-8">
        <img
          src="/placeholder.svg"
          alt="Product Image"
          width={600}
          height={900}
          className="aspect-[2/3] object-cover border w-full rounded-lg overflow-hidden"
        />
        <div className="grid gap-4">
          <div className="grid gap-2">
            <h1 className="font-bold text-3xl lg:text-4xl">Acme Prism T-Shirt</h1>
            <div className="flex items-center gap-0.5">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            </div>
          </div>
          <div className="text-sm leading-loose text-muted-foreground">
            <p>
              Introducing the Acme Prism T-Shirt, a perfect blend of style and comfort for the modern individual. This
              tee is crafted with a meticulous composition of 60% combed ringspun cotton and 40% polyester jersey,
              ensuring a soft and breathable fabric that feels gentle against the skin.
            </p>
            <p>
              The design of the Acme Prism T-Shirt is as striking as it is comfortable. The shirt features a unique
              prism-inspired pattern that adds a modern and eye-catching touch to your ensemble.
            </p>
          </div>
          <div className="flex items-center gap-4">
            <h2 className="text-4xl font-bold">$49.99</h2>
            <Button size="lg">Add to Cart</Button>
          </div>
        </div>
      </div>
      <div className="grid gap-6 md:gap-8">
        <Card>
          <CardHeader>
            <CardTitle>Product Specifications</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="grid gap-2">
              <h3 className="font-medium">Materials</h3>
              <p>60% combed ringspun cotton, 40% polyester jersey</p>
            </div>
            <div className="grid gap-2">
              <h3 className="font-medium">Care Instructions</h3>
              <p>Machine wash cold, tumble dry low</p>
            </div>
            <div className="grid gap-2">
              <h3 className="font-medium">Dimensions</h3>
              <p>Length: 27 inches, Chest: 42 inches</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Customer Reviews</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="grid gap-4">
                <div className="flex gap-4 items-start">
                  <div className="grid gap-0.5 text-sm">
                    <h3 className="font-semibold">Sarah Johnson</h3>
                    <time className="text-sm text-muted-foreground">2 days ago</time>
                  </div>
                  <div className="flex items-center gap-0.5 ml-auto">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                </div>
                <div className="text-sm leading-loose text-muted-foreground">
                  <p>
                    I've been experimenting with my LuminaCook Multi-Function Air Fryer for a few weeks now, and it's
                    been a versatile addition to my kitchen. It's great for making crispy fries, chicken wings, and even
                    some healthier options.
                  </p>
                </div>
              </div>
            </div>
            <Separator className="my-6" />
            <div className="flex gap-4">
              <Avatar className="w-10 h-10 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div className="grid gap-4">
                <div className="flex gap-4 items-start">
                  <div className="grid gap-0.5 text-sm">
                    <h3 className="font-semibold">Alex Smith</h3>
                    <time className="text-sm text-muted-foreground">3 weeks ago</time>
                  </div>
                  <div className="flex items-center gap-0.5 ml-auto">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                </div>
                <div className="text-sm leading-loose text-muted-foreground">
                  <p>
                    I recently purchased the SparkleShine Home Cleaning Robot, and it has been a game-changer in my
                    life. I used to spend hours every weekend cleaning my house, but now I can simply turn on this
                    little robot and let it do the work. It's incredibly efficient, navigating around obstacles with
                    ease. The only reason I didn't give it a perfect 5-star rating is that it occasionally gets stuck
                    under low furniture. Overall, it's been a great addition to my home, saving me time and effort.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
